# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 04:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qiushipro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=188)),
                ('content', models.TextField()),
                ('img_url', models.CharField(max_length=250)),
                ('localImgPath', models.CharField(max_length=250)),
                ('funny_num', models.CharField(max_length=20)),
                ('comment_num', models.CharField(max_length=20)),
                ('comment_list', models.TextField()),
                ('clsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider01.ClsTable')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '糗事百科',
            },
        ),
    ]
