# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapp', '0003_auto_20181111_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jiziconpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=255, null=True)),
                ('intro', models.CharField(max_length=255, null=True)),
                ('content_list', models.TextField(null=True)),
                ('title', models.CharField(max_length=188, null=True)),
                ('img_url', models.CharField(max_length=250, null=True)),
                ('localImgPath', models.CharField(max_length=250, null=True)),
                ('clsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderapp.ClsTable')),
            ],
        ),
        migrations.CreateModel(
            name='Juzitagtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_time', models.CharField(max_length=255, null=True)),
                ('uuid', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('intro', models.CharField(max_length=255, null=True)),
                ('content_list', models.TextField(null=True)),
                ('title', models.CharField(max_length=188, null=True)),
                ('img_url', models.CharField(max_length=250, null=True)),
                ('localImgPath', models.CharField(max_length=250, null=True)),
                ('clsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderapp.ClsTable')),
            ],
        ),
    ]
