# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderapp', '0004_jiziconpro_juzitagtable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jiziconpro',
            new_name='Juziconpro',
        ),
    ]
