# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='Discount',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
