# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='pName',
            field=models.CharField(max_length=20),
        ),
    ]
