# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0002_auto_20181210_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ahthor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihu.Author'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='zhihu.Author'),
        ),
    ]
